# Generated by Django 4.0.2 on 2022-02-22 09:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.UUIDField(default=uuid.UUID('cceea734-10ad-47a0-bcbf-fd3bd9b79504'), primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=64, unique=True, verbose_name='логин пользователя')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email пользователя')),
                ('first_name', models.CharField(max_length=64, verbose_name='имя пользователя')),
                ('last_name', models.CharField(max_length=64, null=True, verbose_name='фамилия пользователя')),
                ('birthday_year', models.PositiveIntegerField()),
            ],
        ),
    ]
