# Generated by Django 4.0.2 on 2022-04-03 16:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authapp', '0001_initial'),
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='initiator_project',
        ),
        migrations.AddField(
            model_name='project',
            name='user_on_project',
            field=models.ManyToManyField(through='mainapp.UserOnProject', to=settings.AUTH_USER_MODEL, verbose_name='пользователь на проекте'),
        ),
        migrations.AddField(
            model_name='todo',
            name='user_on_todo',
            field=models.ManyToManyField(through='mainapp.Executor', to='mainapp.UserOnProject'),
        ),
    ]
